### PR TITLE
Ft read and rate articles 162414238

### PR DESCRIPTION
**Pull request by ebzeal**
#### What does this PR do?
 Users can rate an article

#### Description of Task to be completed?
Users should be able to like and or dislike articles(Changed to rating by PO)

#### Screenshot
screenshot 2019-02-24 at 1 00 59 pm

#### What are the relevant pivotal tracker stories?
[Users can rate article](https://www.pivotaltracker.com/n/projects/2229851/stories/162414238)

### CODE REVIEW

**Comment by rafmme** [comment]
LGTM, yet

**Comment by Makwe-O** [comment]
LGTM, yet

**Comment by Makwe-O** [comment]
LGTM, yet

**Comment by tejiri4** [comment]
LGTM,yet.

**Pull request merged**
